### ISSUE TITLE
napalm.get not working for Arista EOS( Socket error during eAPI connection:)

### ISSUE THREAD

**Issue by netwninja** [StackStorm-Exchange/stackstorm-napalm#59]
None of the napalm pack get actions working for Arista EOS. 

ARISTA VERSION

```
EOS-A#show version 
Arista vEOS
Hardware version:    
Serial number:       
System MAC address:  5000.002f.d8fe

Software image version: 4.21.1.1F
Architecture:           i386
Internal build version: 4.21.1.1F-10146868.42111F
Internal build ID:      ed3973a9-79db-4acc-b9ac-19b9622d23e2

Uptime:                 0 weeks, 0 days, 1 hours and 12 minutes
Total memory:           2016668 kB
Free memory:            1145792 kB

```

NAPALM VERSION

```
 pip freeze | grep napalm
napalm==2.4.0
```

COMMAND USED 

```
st2 run napalm.get_lldp_neighbors hostname=EOS-A 

```

TRACEBACK
```

.
id: 5d9ac42e91b277310898487d
status: failed
parameters: 
  hostname: EOS-A
result: 
  exit_code: 1
  result: None
  stderr: "No handlers could be found for logger "pyeapi.eapilib"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/get_lldp_neighbors.py", line 10, in run
    with self.get_driver(**std_kwargs) as device:
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/base.py", line 47, in __enter__
    self.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
"
  stdout: ''

```

**Comment by nmaludy** [comment]
Couple things to check:

1. make sure you have the HTTP API enabled on the Arista device. I know by default they come with it turned off.
2. Try connecting via http and see if that helps at all. if it does, then your HTTP config on the Arista device isn't setup for ssl https connections.

**Comment by netwninja** [comment]
The Arista API is enabled as we can see in the below output. Also, it's working fine when i try to access the Arista switch directly via browser 

```
EOS-A#show management api http-commands 
Enabled:            Yes
HTTPS server:       running, set to use port 443
HTTP server:        shutdown, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               default
Hits:               9
Last hit:           28820 seconds ago
Bytes in:           1169
Bytes out:          7970
**Requests:           3**
**Commands:           3**
Duration:           0.232 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
   User          Requests       Bytes in       Bytes out    Last hit          
------------- -------------- -------------- --------------- ----------------- 
   ansible       3              1169           7970         28820 seconds ago 

URLs                                   
-------------------------------------- 
Ethernet2   : https://192.168.10.1:443 
Management1 : https://10.0.0.165:443   

```

Now i went ahead and enabled HTTP, same results 

Arista output 

```
EOS-A#show management api http-commands
Enabled:            Yes
HTTPS server:       shutdown, set to use port 443
HTTP server:        running, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               default
Hits:               9
Last hit:           29353 seconds ago
Bytes in:           1169
Bytes out:          7970
Requests:           3
Commands:           3
Duration:           0.232 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
   User          Requests       Bytes in       Bytes out    Last hit          
------------- -------------- -------------- --------------- ----------------- 
   ansible       3              1169           7970         29353 seconds ago 

URLs                                 
------------------------------------ 
Ethernet2   : http://192.168.10.1:80 
Management1 : http://10.0.0.165:80   

```

OUTPUT FROM STACKSTORM

```
st2 run napalm.get_lldp_neighbors hostname=EOS-A port=80

.
id: 5d9b48b491b27731089848b0
status: failed
parameters: 
  hostname: EOS-A
  port: '80'
result: 
  exit_code: 1
  result: None
  stderr: "No handlers could be found for logger "pyeapi.eapilib"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/get_lldp_neighbors.py", line 10, in run
    with self.get_driver(**std_kwargs) as device:
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/base.py", line 47, in __enter__
    self.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
"
  stdout: ''
```

NAPALM COMMAND OUTPUT STACKSTORM SERVER

```
(napalm) devops@StackSorm:/opt/stackstorm/virtualenvs$  napalm --vendor eos --user ansible --password ansible123 --optional_args 'port=80, config_lock=False' eos-a call get_facts
No handlers could be found for logger "pyeapi.eapilib"
2019-10-07 14:21:40,461 - napalm - ERROR - open - Failed: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

================= Traceback =================

Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/napalm/bin/napalm", line 10, in <module>
    sys.exit(main())
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/clitools/cl_napalm.py", line 309, in main
    run_tests(args)
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/clitools/cl_napalm.py", line 284, in run_tests
    call_open_device(device)
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/clitools/cl_napalm.py", line 31, in wrapper
    r = func(*args, **kwargs)
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/clitools/cl_napalm.py", line 208, in call_open_device
    return device.open()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
(napalm) devops@StackSorm:/opt/stackstorm/virtualenvs$ 

```

NAPALM COMMAND OUTPUT FROM LINUX SERVER 

```
napalm --vendor eos --user ansible --password ansible123 --optional_args 'port=80, config_lock=False' eos-a call get_facts
No handlers could be found for logger "pyeapi.eapilib"
2019-10-07 14:24:36,940 - napalm - ERROR - open - Failed: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

================= Traceback =================

Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 285, in main
    run_tests(args)
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 260, in run_tests
    call_open_device(device)
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/clitools/cl_napalm.py", line 192, in call_open_device
    return device.open()
  File "/usr/local/lib/python2.7/dist-packages/napalm/eos/eos.py", line 147, in open
    raise ConnectionException(py23_compat.text_type(ce))
napalm.base.exceptions.ConnectionException: Socket error during eAPI connection: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
root@napalm:~# 

```

**Comment by netwninja** [comment]
To me it seems like the box or server is trying tom run  this command locally even before sending the request out on wire to Arista switch and that's where it's failing. 

```
128          try:
   129              connection = self.transport_class(
   130                  host=self.hostname,
   131                  username=self.username,
   132                  password=self.password,
   133                  timeout=self.timeout,
   134                  **self.eapi_kwargs
   135              )
   136
   137              if self.device is None:
   138                  self.device = pyeapi.client.Node(connection, enablepwd=self.enablepwd)
   139              # does not raise an Exception if unusable
   140
   141              # let's try to run a very simple command
   142              self.device.run_commands(["show clock"], encoding="text")
   143          except ConnectionError as ce:
   144              # and this is raised either if device not avaiable
   145              # either if HTTP(S) agent is not enabled
   146              # show management api http-commands
   147              raise ConnectionException(py23_compat.text_type(ce))
```
